/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClansRouteImport } from './routes/clans'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SocietiesRouteImport } from './routes/societies'
import { Route as WorldRouteImport } from './routes/world'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as ClansSlugRouteImport } from './routes/clans.$slug'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as CommunitiesCreateRouteImport } from './routes/communities.create'
import { Route as SocietiesSlugRouteImport } from './routes/societies.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansRoute = ClansRouteImport.update({
  id: '/clans',
  path: '/clans',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesRoute = SocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansSlugRoute = ClansSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClansRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesRoute,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunitiesRoute,
} as any)
const CommunitiesCreateRoute = CommunitiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CommunitiesRoute,
} as any)
const SocietiesSlugRoute = SocietiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SocietiesRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clans': typeof ClansRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/societies': typeof SocietiesRouteWithChildren
  '/world': typeof WorldRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/clans/$slug': typeof ClansSlugRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/societies/$slug': typeof SocietiesSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clans': typeof ClansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/societies': typeof SocietiesRouteWithChildren
  '/world': typeof WorldRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/clans/$slug': typeof ClansSlugRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/societies/$slug': typeof SocietiesSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/communities': typeof CommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clans': typeof ClansRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/societies': typeof SocietiesRouteWithChildren
  '/world': typeof WorldRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/clans/$slug': typeof ClansSlugRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/societies/$slug': typeof SocietiesSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clans'
    | '/communities'
    | '/profile'
    | '/societies'
    | '/world'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/clans/$slug'
    | '/communities/$slug'
    | '/communities/create'
    | '/societies/$slug'
    | '/u/$username'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clans'
    | '/profile'
    | '/societies'
    | '/world'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/clans/$slug'
    | '/communities/$slug'
    | '/communities/create'
    | '/societies/$slug'
    | '/u/$username'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/clans'
    | '/communities'
    | '/profile'
    | '/societies'
    | '/world'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/clans/$slug'
    | '/communities/$slug'
    | '/communities/create'
    | '/societies/$slug'
    | '/u/$username'
    | '/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClansRoute: typeof ClansRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SocietiesRoute: typeof SocietiesRouteWithChildren
  WorldRoute: typeof WorldRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans': {
      id: '/clans'
      path: '/clans'
      fullPath: '/clans'
      preLoaderRoute: typeof ClansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societies': {
      id: '/societies'
      path: '/societies'
      fullPath: '/societies'
      preLoaderRoute: typeof SocietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$slug': {
      id: '/clans/$slug'
      path: '/$slug'
      fullPath: '/clans/$slug'
      preLoaderRoute: typeof ClansSlugRouteImport
      parentRoute: typeof ClansRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/communities/create': {
      id: '/communities/create'
      path: '/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof CommunitiesCreateRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/societies/$slug': {
      id: '/societies/$slug'
      path: '/$slug'
      fullPath: '/societies/$slug'
      preLoaderRoute: typeof SocietiesSlugRouteImport
      parentRoute: typeof SocietiesRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClansRouteChildren {
  ClansSlugRoute: typeof ClansSlugRoute
}

const ClansRouteChildren: ClansRouteChildren = {
  ClansSlugRoute: ClansSlugRoute,
}

const ClansRouteWithChildren = ClansRoute._addFileChildren(ClansRouteChildren)

interface CommunitiesRouteChildren {
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  CommunitiesCreateRoute: typeof CommunitiesCreateRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  CommunitiesCreateRoute: CommunitiesCreateRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface SocietiesRouteChildren {
  SocietiesSlugRoute: typeof SocietiesSlugRoute
}

const SocietiesRouteChildren: SocietiesRouteChildren = {
  SocietiesSlugRoute: SocietiesSlugRoute,
}

const SocietiesRouteWithChildren = SocietiesRoute._addFileChildren(
  SocietiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClansRoute: ClansRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SocietiesRoute: SocietiesRouteWithChildren,
  WorldRoute: WorldRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
