/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WorldRouteImport } from './routes/world'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as CommunitiesCreateRouteImport } from './routes/communities.create'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as SocietiesRouteImport } from './routes/societies'
import { Route as SocietiesSlugRouteImport } from './routes/societies.$slug'
import { Route as ClansRouteImport } from './routes/clans'
import { Route as ClansSlugRouteImport } from './routes/clans.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCreateRoute = CommunitiesCreateRouteImport.update({
  id: '/communities/create',
  path: '/communities/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesRoute = SocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesSlugRoute = SocietiesSlugRouteImport.update({
  id: '/societies/$slug',
  path: '/societies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansRoute = ClansRouteImport.update({
  id: '/clans',
  path: '/clans',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansSlugRoute = ClansSlugRouteImport.update({
  id: '/clans/$slug',
  path: '/clans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/world': typeof WorldRoute
  '/communities': typeof CommunitiesRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/societies': typeof SocietiesRoute
  '/societies/$slug': typeof SocietiesSlugRoute
  '/clans': typeof ClansRoute
  '/clans/$slug': typeof ClansSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/world': typeof WorldRoute
  '/communities': typeof CommunitiesRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/societies': typeof SocietiesRoute
  '/societies/$slug': typeof SocietiesSlugRoute
  '/clans': typeof ClansRoute
  '/clans/$slug': typeof ClansSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/world': typeof WorldRoute
  '/communities': typeof CommunitiesRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/societies': typeof SocietiesRoute
  '/societies/$slug': typeof SocietiesSlugRoute
  '/clans': typeof ClansRoute
  '/clans/$slug': typeof ClansSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/world'
    | '/communities'
    | '/communities/create'
    | '/communities/$slug'
    | '/societies'
    | '/societies/$slug'
    | '/clans'
    | '/clans/$slug'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/world'
    | '/communities'
    | '/communities/create'
    | '/communities/$slug'
    | '/societies'
    | '/societies/$slug'
    | '/clans'
    | '/clans/$slug'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/world'
    | '/communities'
    | '/communities/create'
    | '/communities/$slug'
    | '/societies'
    | '/societies/$slug'
    | '/clans'
    | '/clans/$slug'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  WorldRoute: typeof WorldRoute
  CommunitiesRoute: typeof CommunitiesRoute
  CommunitiesCreateRoute: typeof CommunitiesCreateRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  SocietiesRoute: typeof SocietiesRoute
  SocietiesSlugRoute: typeof SocietiesSlugRoute
  ClansRoute: typeof ClansRoute
  ClansSlugRoute: typeof ClansSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/profile': { id: '/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/world': { id: '/world'; path: '/world'; fullPath: '/world'; preLoaderRoute: typeof WorldRouteImport; parentRoute: typeof rootRouteImport }
    '/communities': { id: '/communities'; path: '/communities'; fullPath: '/communities'; preLoaderRoute: typeof CommunitiesRouteImport; parentRoute: typeof rootRouteImport }
    '/communities/create': { id: '/communities/create'; path: '/communities/create'; fullPath: '/communities/create'; preLoaderRoute: typeof CommunitiesCreateRouteImport; parentRoute: typeof rootRouteImport }
    '/communities/$slug': { id: '/communities/$slug'; path: '/communities/$slug'; fullPath: '/communities/$slug'; preLoaderRoute: typeof CommunitiesSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/societies': { id: '/societies'; path: '/societies'; fullPath: '/societies'; preLoaderRoute: typeof SocietiesRouteImport; parentRoute: typeof rootRouteImport }
    '/societies/$slug': { id: '/societies/$slug'; path: '/societies/$slug'; fullPath: '/societies/$slug'; preLoaderRoute: typeof SocietiesSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/clans': { id: '/clans'; path: '/clans'; fullPath: '/clans'; preLoaderRoute: typeof ClansRouteImport; parentRoute: typeof rootRouteImport }
    '/clans/$slug': { id: '/clans/$slug'; path: '/clans/$slug'; fullPath: '/clans/$slug'; preLoaderRoute: typeof ClansSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/callback': { id: '/auth/callback'; path: '/auth/callback'; fullPath: '/auth/callback'; preLoaderRoute: typeof AuthCallbackRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/forgot-password': { id: '/auth/forgot-password'; path: '/auth/forgot-password'; fullPath: '/auth/forgot-password'; preLoaderRoute: typeof AuthForgotPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/login': { id: '/auth/login'; path: '/auth/login'; fullPath: '/auth/login'; preLoaderRoute: typeof AuthLoginRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/reset-password': { id: '/auth/reset-password'; path: '/auth/reset-password'; fullPath: '/auth/reset-password'; preLoaderRoute: typeof AuthResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/signup': { id: '/auth/signup'; path: '/auth/signup'; fullPath: '/auth/signup'; preLoaderRoute: typeof AuthSignupRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/verify-email': { id: '/auth/verify-email'; path: '/auth/verify-email'; fullPath: '/auth/verify-email'; preLoaderRoute: typeof AuthVerifyEmailRouteImport; parentRoute: typeof rootRouteImport }
    '/u/$username': { id: '/u/$username'; path: '/u/$username'; fullPath: '/u/$username'; preLoaderRoute: typeof UUsernameRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  WorldRoute: WorldRoute,
  CommunitiesRoute: CommunitiesRoute,
  CommunitiesCreateRoute: CommunitiesCreateRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  SocietiesRoute: SocietiesRoute,
  SocietiesSlugRoute: SocietiesSlugRoute,
  ClansRoute: ClansRoute,
  ClansSlugRoute: ClansSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
